### ISSUE TITLE
Debian Linux OS

### ISSUE THREAD

**Issue by YasinDehfuli** [R1maro/day-night-background#1]
i Have some Graphic bugs on Debian OS that  i cant see this page normally

**Comment by R1maro** [comment]
> i Have some Graphic bugs on Debian OS that i cant see this page normally

I think its about your OS/first check you can't solve the problem from your OS

**Comment by YasinDehfuli** [comment]
i think i have some graphic bugs on my debian linux os ; thanks for your help

**Comment by R1maro** [comment]
> i think i have some graphic bugs on my debian linux os ; thanks for your help

Yw
